### ISSUE TITLE
tanx: frame rate drops significantly with 4+ players

### ISSUE THREAD

**Issue by BKStephens** [SeaRbSg/elixir#11]

**Comment by dazuma** [comment]
Did some investigation this afternoon. The game core (i.e. all the game updates and collision checks and stuff) seems fast, even when a bunch of tanks are in play. However, when you connect a bunch of clients that are hitting the websockets and getting views, it eats up cpu.

We can verify this by putting tabs in the background in chrome: that stops the window animation frames from firing, which in turn stops all the traffic on the websocket. If lots of tabs are open with lots of tanks, beam starts eating cpu on the server, but if the tabs are backgrounded, beam stays pretty quiet.

Not yet sure exactly what in the view process is slow. Possibilities include the JSON serialization, or the player-specific view computation (which is currently bottlenecked into the ArenaView process).

**Comment by dazuma** [comment]
Ran some benchmarks and learned something REALLY interesting. JSON serialization using the Poison library (which is what Phoenix uses by default) can be slow, especially if you serialize structs. Serializing a struct can be at least an order of magnitude, sometimes TWO orders of magnitude, slower than serializing the equivalent map. I think this is the bottleneck; I'll retool ArenaView to send raw maps and see if that solves our issue.

**Comment by BitBrit** [comment]
Nice work, Daniel! Out of interest, how did you do the benchmarking?

**Comment by dazuma** [comment]
Erlang's timer module: http://www.erlang.org/doc/man/timer.html#tc-1. I'd been measuring various processes in the system (ArenaUpdater, ArenaView, Tank, Player, etc.) and began to suspect JSON serialization, so I wrote up some toy test cases for Poison. The differences are stark. No idea why.

**Comment by dazuma** [comment]
Changed the per-frame serialization to use maps rather than structs. That seems to have greatly improved things, so I'm going to go ahead and close this. We'll need to continue to look at the performance and make incremental improvements.

**Comment by dazuma** [comment]
Incidentally, it looks like this is a known issue. e.g. https://github.com/devinus/poison/issues/38
