### ISSUE TITLE
Flickering tanks

### ISSUE THREAD

**Issue by dazuma** [SeaRbSg/elixir#23]
I've observed tanks "flickering" (i.e. briefly disappearing and then reappearing) during animation. This seems to happen more often when talking to the remote server, and maybe more often when more players are connected. Investigate why.

One stab-in-the-dark theory: maybe this happens when rendering happens out of sync with the window refresh rate?

**Comment by BKStephens** [comment]
I think this may have been fixed by 5af7bd1, but I will keep this issue open in the meantime incase it crops up again.

**Comment by dazuma** [comment]
Haven't seen this anymore. I think Ben's fix worked. Closing.
