### ISSUE TITLE
Name fields should be escaped

### ISSUE THREAD

**Issue by kylerippey** [SeaRbSg/elixir#48]
Right now the name field is vulnerable to all kinds of nasty manipulation. We should definitely fix that.

**Comment by BKStephens** [comment]
<p style="font-size:96px;">But why?</p>

**Comment by BitBrit** [comment]
Intending to escape the field by any means possible.

**Comment by BKStephens** [comment]
`git show 0461531`

**Comment by BitBrit** [comment]
I have pushed a fix for this. I don't know how "right" it is or even if I have done it in the best way so some education in this matter would be welcomed. Either way, it seems to work in that it now ignores html and javascript entered into the name field.
