### ISSUE TITLE
Need access for eqdw

### ISSUE THREAD

**Issue by eqdw** [SeaRbSg/elixir#5]
Spoke to a fellow (forget his name, but he had an accent) at last night's Seattle.rb meetup. I'd like to join your cool kids Elixir club 

![giphy](https://cloud.githubusercontent.com/assets/46030/7053277/c0c2cadc-dde8-11e4-8301-2b661e0f39fd.gif)

**Comment by zenspider** [comment]
Invite sent. cc @dazuma
