### ISSUE TITLE
Fix the 4 failing tests

### ISSUE THREAD

**Issue by BKStephens** [SeaRbSg/elixir#57]
1) test one player fires 2 missiles (Tanx.BasicTanksTest)
     test/core/basic_tanks_test.exs:91
     Assertion with == failed
     code: view == %Tanx.Core.View.Arena{missiles: [%Tanx.Core.View.Missile{is_mine: true, x: 10.0}, %Tanx.Core.View.Missile{is_mine: true, x: 10.0}], tanks: [%Tanx.Core.View.Tank{is_me: true, name: "Kyle", armor: 1.0}]}
     lhs:  %Tanx.Core.View.Arena{entry_points_available: %{},
            explosions: [%Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0},
             %Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0}], missiles: [], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     rhs:  %Tanx.Core.View.Arena{entry_points_available: %{}, explosions: [],
            missiles: [%Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0},
             %Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0}], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     stacktrace:
       test/core/basic_tanks_test.exs:102

  2) test one player fires missiles too quickly (Tanx.BasicTanksTest)
     test/core/basic_tanks_test.exs:70
     Assertion with == failed
     code: view == %Tanx.Core.View.Arena{missiles: [%Tanx.Core.View.Missile{is_mine: true, x: 10.0}], tanks: [%Tanx.Core.View.Tank{is_me: true, name: "Kyle", armor: 1.0}]}
     lhs:  %Tanx.Core.View.Arena{entry_points_available: %{},
            explosions: [%Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0}], missiles: [],
            powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     rhs:  %Tanx.Core.View.Arena{entry_points_available: %{}, explosions: [],
            missiles: [%Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0}], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     stacktrace:
       test/core/basic_tanks_test.exs:80

  3) test one player fires a missile (Tanx.BasicTanksTest)
     test/core/basic_tanks_test.exs:51
     Assertion with == failed
     code: view == %Tanx.Core.View.Arena{missiles: [%Tanx.Core.View.Missile{is_mine: true, x: 10.0}], tanks: [%Tanx.Core.View.Tank{is_me: true, name: "Kyle", armor: 1.0}]}
     lhs:  %Tanx.Core.View.Arena{entry_points_available: %{},
            explosions: [%Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0}], missiles: [],
            powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     rhs:  %Tanx.Core.View.Arena{entry_points_available: %{}, explosions: [],
            missiles: [%Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0}], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     stacktrace:
       test/core/basic_tanks_test.exs:59

  4) test one player fires a too many missiles (Tanx.BasicTanksTest)
     test/core/basic_tanks_test.exs:120
     Assertion with == failed
     code: view == %Tanx.Core.View.Arena{missiles: [%Tanx.Core.View.Missile{is_mine: true, x: 10.0}, %Tanx.Core.View.Missile{is_mine: true, x: 10.0}, %Tanx.Core.View.Missile{is_mine: true, x: 10.0}, %Tanx.Core.View.Missile{is_mine: true,
x: 10.0}, %Tanx.Core.View.Missile{is_mine: true, x: 10.0}], tanks: [%Tanx.Core.View.Tank{is_me: true, name: "Kyle", armor: 1.0}]}
     lhs:  %Tanx.Core.View.Arena{entry_points_available: %{},
            explosions: [%Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0},
             %Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0},
             %Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0},
             %Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0},
             %Tanx.Core.View.Explosion{age: 0.0, radius: 0.5, sound: nil, x: 10.5, y: 0.0}], missiles: [], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     rhs:  %Tanx.Core.View.Arena{entry_points_available: %{}, explosions: [],
            missiles: [%Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0},
             %Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0},
             %Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0},
             %Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0},
             %Tanx.Core.View.Missile{hx: 0.0, hy: 0.0, is_mine: true, x: 10.0, y: 0.0}], powerups: [],
            tanks: [%Tanx.Core.View.Tank{armor: 1.0, heading: 0.0, is_me: true, max_armor: 1.0, name: "Kyle", radius: 0.5,
              tread: 0.0, x: 0.0, y: 0.0}]}
     stacktrace:
       test/core/basic_tanks_test.exs:139

**Comment by BKStephens** [comment]
I ran git bisect, and I believe "1) test one player fires 2 missiles (Tanx.BasicTanksTest)" broke with 1d20cfaba9eacc358fd6cdd44336b33cb267d434.

**Comment by dazuma** [comment]
Fixes checked in.
