### ISSUE TITLE
Try multiple token-based backpressure instead of a single request-response

### ISSUE THREAD

**Issue by dazuma** [SeaRbSg/elixir#58]
We might be able to get a frame rate improvement.

**Comment by BitBrit** [comment]
I'd love to see what you think is the best way to do this. Also if I can participate in the fix, let me know! :+1:

**Comment by dazuma** [comment]
I implemented this in https://github.com/SeaRbSg/elixir/commit/f5213d3e8639433c3e4e806244d0fe433ae0bfaa (see changes to animate.js). It seems to do well on my home connection to the staging server. I can easily get up to 60fps (the javascript window refresh limit) with a buffer size of 4. For now I made the buffer size adaptive where it will measure the current fps and try to resize the buffer to keep the frame rate between 30 and 50. It will be interesting to see how this does on Caffe Vita's wifi.
