### ISSUE TITLE
tanx: disable entry points when tanks are camped on them

### ISSUE THREAD

**Issue by BKStephens** [SeaRbSg/elixir#6]
We are already doing this, but the area is too big. Lets refine this so that the entry point is only disabled when a tank is directly on top of it.

**Comment by dazuma** [comment]
Made the entry areas smaller, and adjusted the maze accordingly. I don't want to restrict entry only when a tank is on top of the entry point itself, because it encourages tanks to enter when another tank is just leaving the entry point, and blowing that tank up immediately.
